### ISSUE TITLE
実際に計算したanswerをもとにdbにデータを格納する

### ISSUE THREAD

**Issue by DaisukeMiyazaki** [kanakof/personality_django#11]
性格診断で作ったPOSTした際に、bodyの結果をanswerでdbに格納する

**Comment by kanakof** [comment]
@DaisukeMiyazaki 
こちら、pull requestで別途レビュー頂いたので、closeします！

**Comment by kanakof** [comment]
@DaisukeMiyazaki
こちら、pull requestで別途レビュー頂いたので、closeします！
